spring:
  sql:
    init:
      mode: always
      platform: postgresql
      # schema-locations: classpath:db/postgres/schema.sql
      data-locations: classpath:db/postgres/data.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/booksdb
    driver-class-name: org.postgresql.Driver
    username: dbuser
    password: dbpassword
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 20000
      pool-name: HikariCP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

logging:
  level:
    root: INFO
    com.sonnesen.book_reading_tracker: DEBUG