name: Trigger auto deployment for aca-fiap-dsv-bra

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  #push:
    #branches: 
    #  [ feature/azure ]
    #paths:
    #- '**'
    #- '.github/workflows/aca-fiap-dsv-bra-AutoDeployTrigger-d3da9121-5aca-4a4f-b08f-0eb9bbae4ecc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ACAFIAPDSVBRA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ACAFIAPDSVBRA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ACAFIAPDSVBRA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.ACAFIAPDSVBRA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACAFIAPDSVBRA_REGISTRY_PASSWORD }}
          containerAppName: aca-fiap-dsv-bra
          resourceGroup: rg-fiap-live
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


