name: CI/CD

on: 
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn -B -DskipTests clean package 
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Deploy step
      run: echo "Deploy step"

  #  - uses: azure/login@v2
  #    with:
  #      creds: ${{ secrets.AZURE_CREDENTIALS }}

  #  - name: Azure CLI script
  #    uses: azure/cli@v2
  #    with:
  #      azcliversion: latest
  #      inlineScript: |
  #        az account show